name: Frontend Test
on:
  pull_request:
    paths:
      - frontend/**
jobs:
  frontend-format-linting-check:
    name: Code format and lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Format code
        run: |
          npm install prettier@2.8.8 --prefix ./frontend
          make prettier-check
      - name: Lint code
        run: |
          cd frontend
          npm ci --no-audit
          npm run lint-check
  frontend-unit-tests:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Fetch Kubeflow and install common code dependencies
        run: |
          COMMIT=$(cat frontend/COMMIT)
          cd /tmp && git clone https://github.com/kubeflow/kubeflow.git
          cd kubeflow
          git checkout $COMMIT
          cd components/crud-web-apps/common/frontend/kubeflow-common-lib
          # Patch SCSS files to fix tilde imports
          find . -name "*.scss" -exec sed -i "s|@use '~@angular/material' as mat;|@use '@angular/material' as mat;|" {} \;
          npm ci --no-audit
          npm run build
          mkdir -p /home/runner/work/models-web-app/models-web-app/frontend/node_modules/kubeflow/styles
          cp -r dist/kubeflow/styles/* /home/runner/work/models-web-app/models-web-app/frontend/node_modules/kubeflow/styles/
      - name: Install MWA dependencies
        run: |
          cd frontend
          npm ci --no-audit
      - name: Run unit tests
        run: |
          cd frontend
          npm run test:prod